spring:
  minio:
    endpoint: "http://192.168.5.1:9000"
    username: "minioadmin"
    password: "minioadmin"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/jwt_database
  security:
    jwt:
      key: key_for_me
  mail:
    host: smtp.163.com
    username: Fcoming@163.com
    password: OHHZSXCCCRRXILJJ
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
  weather:
    key: ee2127f1d84a4ff7b6500c24c4cad6c0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB