spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/jwt_database
  security:
    jwt:
      key: key_for_me
  mail:
    host: smtp.163.com
    username: Fcoming@163.com
    password: OHHZSXCCCRRXILJJ
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /